@startuml

title __LINK's Class Diagram__\n

  namespace cn.cdut.link {
    class cn.cdut.link.MainActivity {
        ~ drawables : int[]
        ~ num : HashMap<Integer, Integer>
        # onCreate()
        - getData()
    }
  }
  

  namespace cn.cdut.link {
    class cn.cdut.link.MainActivity.Adapter {
        - list : List<Image>
        + Adapter()
        + getItemCount()
        + onBindViewHolder()
        + onCreateViewHolder()
        + setList()
    }
  }
  

  namespace cn.cdut.link {
    class cn.cdut.link.MainActivity.Adapter.MyHolder {
        - imageView : ImageView
        - itemView : View
        + MyHolder()
    }
  }
  

  namespace cn.cdut.link {
    class cn.cdut.link.MainActivity.Attr {
        ~ pos : int
        ~ var : int
        + Attr()
    }
  }
  

  namespace cn.cdut.link {
    class cn.cdut.link.MainActivity.Image {
        ~ img : int
        ~ visible : boolean
        + Image()
    }
  }
  

  namespace cn.cdut.link {
    class cn.cdut.link.Score {
        + cur : int
        + getCur()
        + setCur()
    }
  }
  

  cn.cdut.link.MainActivity -up-|> androidx.appcompat.app.AppCompatActivity
  cn.cdut.link.MainActivity o-- cn.cdut.link.MainActivity.Adapter : adapter
  cn.cdut.link.MainActivity o-- cn.cdut.link.databinding.ActivityMainBinding : binding
  cn.cdut.link.MainActivity o-- cn.cdut.link.MainActivity.Attr : pre
  cn.cdut.link.MainActivity o-- cn.cdut.link.Score : score
  cn.cdut.link.MainActivity +-down- cn.cdut.link.MainActivity.Adapter
  cn.cdut.link.MainActivity +-down- cn.cdut.link.MainActivity.Attr
  cn.cdut.link.MainActivity +-down- cn.cdut.link.MainActivity.Image
  cn.cdut.link.MainActivity.Adapter -up-|> androidx.recyclerview.widget.RecyclerView.Adapter
  cn.cdut.link.MainActivity.Adapter +-down- cn.cdut.link.MainActivity.Adapter.MyHolder
  cn.cdut.link.MainActivity.Adapter.MyHolder -up-|> androidx.recyclerview.widget.RecyclerView.ViewHolder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
