@startuml

title __APP's Class Diagram__\n

  namespace androidx.databinding {
    class androidx.databinding.DataBinderMapperImpl {
    }
  }
  

  namespace androidx.databinding {
    interface androidx.databinding.DataBindingComponent {
    }
  }
  

  namespace androidx.databinding {
    namespace library.baseAdapters {
      class androidx.databinding.library.baseAdapters.BR {
      }
    }
  }
  

  namespace cn.cdut.link {
    class cn.cdut.link.BR {
    }
  }
  

  namespace cn.cdut.link {
    class cn.cdut.link.BuildConfig {
    }
  }
  

  namespace cn.cdut.link {
    class cn.cdut.link.DataBinderMapperImpl {
    }
  }
  

  namespace cn.cdut.link {
    class cn.cdut.link.DataBindingInfo {
    }
  }
  

  namespace cn.cdut.link {
    class cn.cdut.link.MainActivity {
    }
  }
  

  namespace cn.cdut.link {
    class cn.cdut.link.Score {
    }
  }
  

  namespace cn.cdut.link {
    namespace databinding {
      abstract class cn.cdut.link.databinding.ActivityMainBinding {
      }
    }
  }
  

  namespace cn.cdut.link {
    namespace databinding {
      class cn.cdut.link.databinding.ActivityMainBindingImpl {
      }
    }
  }
  

  androidx.databinding.DataBinderMapperImpl -up-|> androidx.databinding.MergedDataBinderMapper
  cn.cdut.link.DataBinderMapperImpl -up-|> androidx.databinding.DataBinderMapper
  cn.cdut.link.MainActivity -up-|> androidx.appcompat.app.AppCompatActivity
  cn.cdut.link.MainActivity o-- cn.cdut.link.MainActivity.Adapter : adapter
  cn.cdut.link.MainActivity o-- cn.cdut.link.databinding.ActivityMainBinding : binding
  cn.cdut.link.MainActivity o-- cn.cdut.link.MainActivity.Attr : pre
  cn.cdut.link.MainActivity o-- cn.cdut.link.Score : score
  cn.cdut.link.databinding.ActivityMainBinding -up-|> androidx.databinding.ViewDataBinding
  cn.cdut.link.databinding.ActivityMainBinding o-- cn.cdut.link.Score : mScore
  cn.cdut.link.databinding.ActivityMainBindingImpl -up-|> cn.cdut.link.databinding.ActivityMainBinding


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
